
import { jsPDF } from "jspdf";
import { pdfColors } from "./pdf-core";

export const addFooter = (doc: jsPDF, pageNum: number, totalPages: number, margin: number) => {
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const footerY = pageHeight - 20;
  
  // Add divider line
  doc.setDrawColor('#E5E5E5');
  doc.setLineWidth(0.5);
  doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
  
  // Add company info
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(pdfColors.mutedTextColor);
  doc.setFontSize(8);
  doc.text("Generated by Bliss Digital Invitations | www.bliss-go.com", margin, footerY);
  
  // Add page number
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin - 25, footerY);
  
  // Add social media icons using the newly uploaded image
  const socialY = footerY + 24; // Moved down by 20px (from 4 to 24)
  const socialX = margin;
  const socialIconHeight = 8; // Fixed height for the social icons
  const socialIconWidth = 8; // Width equal to height to maintain aspect ratio (1:1)
  
  // Add the uploaded social media icons image
  doc.addImage(
    "/lovable-uploads/73967cd6-93e4-42c7-baa5-b0830cffd64c.png", 
    "PNG", 
    socialX, 
    socialY - socialIconHeight, 
    socialIconWidth, 
    socialIconHeight
  );
  
  // Social media handle - positioned next to the icons
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(pdfColors.mutedTextColor);
  doc.setFontSize(8);
  doc.text("weave.bliss", socialX + socialIconWidth + 2, socialY - 2);
};
