
import { jsPDF } from "jspdf";
import { pdfColors } from "./pdf-core";

export const addFooter = (doc: jsPDF, pageNum: number, totalPages: number, margin: number) => {
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const footerY = pageHeight - 20;
  
  // Add divider line
  doc.setDrawColor('#E5E5E5');
  doc.setLineWidth(0.5);
  doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
  
  // Add company info
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(pdfColors.mutedTextColor);
  doc.setFontSize(8);
  doc.text("Generated by Bliss Digital Invitations | www.bliss-go.com", margin, footerY);
  
  // Add page number
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin - 25, footerY);
  
  // Add social media
  const socialY = footerY + 5;
  const socialX = margin;
  const iconSize = 3;
  
  // Instagram icon (simplified square with circle)
  doc.setDrawColor(pdfColors.mutedTextColor);
  doc.setFillColor(pdfColors.mutedTextColor);
  doc.roundedRect(socialX, socialY - iconSize, iconSize, iconSize, 0.8, 0.8, 'FD');
  doc.setDrawColor('#FFFFFF');
  doc.setLineWidth(0.2);
  doc.circle(socialX + iconSize/2, socialY - iconSize/2, iconSize/3, 'S');
  doc.setFillColor('#FFFFFF');
  doc.circle(socialX + iconSize*0.8, socialY - iconSize*0.8, iconSize/6, 'F');
  
  // TikTok icon (simplified musical note)
  doc.setDrawColor(pdfColors.mutedTextColor);
  doc.setFillColor(pdfColors.mutedTextColor);
  doc.setLineWidth(0.5);
  doc.line(socialX + iconSize + 5, socialY - iconSize, socialX + iconSize + 5, socialY);
  doc.line(socialX + iconSize + 5, socialY - iconSize, socialX + iconSize + 7, socialY - iconSize + 1);
  doc.circle(socialX + iconSize + 7, socialY - 1, 1, 'F');
  
  // Social media handle
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(pdfColors.mutedTextColor);
  doc.setFontSize(8);
  doc.text("weave.bliss", socialX + iconSize + 10, socialY - 0.5);
};
